### ISSUE TITLE
Add support for performing additional validation on the `vc.type` 

### ISSUE THREAD

**Issue by jdkizer9** [microsoft/health-cards-validation-SDK#116]
I noticed [here](https://github.com/microsoft/health-cards-validation-SDK/blob/7500a9de85b6355bdc44edb994ed6f5cc3f34657/src/jws-payload.ts#L56) that we verify that the `https://smarthealth.cards#health-card` type is included in the `vc.type` array. However, we're seeing some SHCs in the wild that do not include the additional granular subtypes defined [here](https://spec.smarthealth.cards/vocabulary/#more-granular-sub-types). Would you consider adding an option to add more strict validation on the `vc.type`?

**Comment by christianpaquin** [comment]
Sorry for the delay, I was on the road. Good point, since the spec says these types SHOULD be present, then a warning should be triggered.

Basically, log a warning if these are missing when:

- `https://smarthealth.cards#covid19`:  a covid19 immunization or lab result is present
- `https://smarthealth.cards#immunization`: a FHIR immunization is present
- `https://smarthealth.cards#laboratory`: a FHIR lab is present

We could promote these as errors when validating against the ` usa-covid19-immunization` profile.

**Comment by christianpaquin** [comment]
PR #120 addresses the first two types. For `#laboratory`, I need more info: which FHIR resources corresponds to this type? DiagnosticReport? Specimen? Observation?

@jdkizer9, @jmandel?

**Comment by christianpaquin** [comment]
After discussing with Josh, we'll plan to use the [Observation profile](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/StructureDefinition-covid19-laboratory-result-observation.html) from the Vaccination & Testing IG.

**Comment by christianpaquin** [comment]
Note: we only currently check for covid-related `#laboratory`.  We can expand the scope in later work.
