### ISSUE TITLE
Wrong number of segments in QR code: found 1, expected 2

### ISSUE THREAD

**Issue by cpsi-thrive** [microsoft/health-cards-validation-SDK#73]
Starting on v0.4.5-1 we started receiving a new error indicating "Wrong number of segments in QR code: found 1, expected 2" when testing a QR code image.

As far as we can tell we have followed the health card spec correctly and this error isn't valid.  There are less than 1200 characters in the JWS so we shouldn't have needed to build two QR codes for this example.

Commands:
node . -p qrcode.png -t qr
node . -p qrcode.png -t qr -l debug -f fhir_out.json

![qrcode](https://user-images.githubusercontent.com/66029960/116101393-64f28f80-a673-11eb-8c3c-faa08bd50b3a.png)

**Comment by christianpaquin** [comment]
Yes, that's a recent check we added. The specification says (in the [encoding-chunks-as-qr-codes](https://smarthealth.cards/#encoding-chunks-as-qr-codes)) that "Each chunk of the JWS string value is represented as a QR with two data segments", one for the `shc:/` header in byte encoding, and one for the data in numeric encoding.

Parsing your example returns one segment:
```
[
  {
    type: 'byte',
    bytes: [115, 104, 99, 58, 47, ... ],
    text: 'shc:/5676290952...'
  }
]
```

Compare this with what we get by parsing the `testdata/example-00-g-qr-code-0.png` file:
```
[
  { type: 'byte', bytes: [ 115, 104, 99, 58, 47 ], text: 'shc:/' },
  {
    type: 'numeric',
    text: '5676290...'
  }
]
```

Now, this shouldn't be an error, because your QR is still parsable; we'll downgrade this to a warning.

Which library do you use to generate the QR encoding? Does it have the ability to generate different segments (sometime called chunks, not to be confused with what the health card spec calls chunks). You can see [here](https://github.com/smart-on-fhir/health-cards/blob/main/generate-examples/src/index.ts#L171) an example of the javascript code that is used to generate the examples.

**Comment by christianpaquin** [comment]
> Now, this shouldn't be an error, because your QR is still parsable; we'll downgrade this to a warning.

@jmandel, do you agree? Or should we stick with an error?

**Comment by cpsi-thrive** [comment]
We are using com.google.zxing.qrcode.  Also we are using java not javascript for the programming.

**Comment by jmandel** [comment]
I think this is an *error* rather than a warning, though we may need to tighten up the language in the spec to avoid any ambiguity on this point.

The entire rationale or our numeric encoding scheme is to enable higher-density QRs. If an implementation is allowed to translate a JWS to digits but then to use *byte* encoding instead of *numeric* encoding for those digits, we'd be blowing up payload sizes by **>200%** (i.e., we'd be packing only 5 JWS characters per 10 QR bytes, instead of 12 JWS characters per 10 QR bytes). If this was going to be OK, we'd do better to use some other encoding scheme.

**Comment by jmandel** [comment]
For QR generation in Java, we've seen successful implementations using https://github.com/nayuki/QR-Code-generator (@jdkizer9 are you able to share links to reference / example code?)

**Comment by jdkizer9** [comment]
Confirming that we're using `io.nayuki:qrcodegen`. Our Kotlin implementation is still closed source, so I can't link to it. The gist of it is:

```
@VisibleForTesting
        fun generateQRCode(qrString: String): QrCode {
            val qr = try {
                val qrSegments = QrSegmentAdvanced.makeSegmentsOptimally(
                    qrString,
                    ERROR_CORRECTION_LEVEL,
                    MIN_VERSION,
                    MAX_VERSION
                )
                QrCode.encodeSegments(qrSegments, ERROR_CORRECTION_LEVEL)
            } catch (e: DataTooLongException) {
                Timber.d(e)
                throw QRCodeGeneratorException.PayloadTooLarge(
                    "SMART Health Card QR code payload too large",
                    e
                )
            }
            Timber.d("QR Code version is ${qr.version}")
            return qr
        }
```

Where:
- `qrString` is the full string to be represented by the QR code (e.g., `shc:/1234...` or `shc:/1/2/1234...`)
- `ERROR_CORRECTION_LEVEL` = `QrCode.Ecc.LOW`
- `MIN_VERSION` =  1
- `MAX_VERSION` = 22

**Comment by shanlock** [comment]
Thank you for the suggestion to use io.nayuki:qrcodegen. That is working for us (cpsi-thrive). I appreciate the help! :)
